openapi: 3.0.0
info:
  title: LaraCollab API
  description: Project management and collaboration API
  version: 1.0.0
  contact:
    name: LaraCollab Team
    url: https://lara-collab.com

servers:
  - url: http://lara-collab.test/api
    description: Local development
  - url: https://staging.lara-collab.com/api
    description: Staging environment
  - url: https://api.lara-collab.com
    description: Production environment

tags:
  - name: Authentication
    description: User authentication endpoints
  - name: Projects
    description: Project management
  - name: Tasks
    description: Task management
  - name: Time Logs
    description: Time tracking
  - name: Users
    description: User management
  - name: Permissions
    description: Permission management

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Project:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        client_company_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Task:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        project_id:
          type: integer
        assigned_to_user_id:
          type: integer
          nullable: true
        due_on:
          type: string
          format: date
          nullable: true
        completed_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ProjectNote:
      type: object
      properties:
        id:
          type: integer
        project_id:
          type: integer
        title:
          type: string
        content:
          type: string
        pinned:
          type: boolean
        created_by:
          type: integer
        created_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

paths:
  /login:
    post:
      tags:
        - Authentication
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /projects:
    get:
      tags:
        - Projects
      summary: List all projects
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: per_page
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Project'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      current_page:
                        type: integer
                      last_page:
                        type: integer

    post:
      tags:
        - Projects
      summary: Create new project
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - client_company_id
              properties:
                name:
                  type: string
                description:
                  type: string
                client_company_id:
                  type: integer
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /projects/{project}/notes:
    get:
      tags:
        - Projects
      summary: Get project notes
      security:
        - bearerAuth: []
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of project notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectNote'

    post:
      tags:
        - Projects
      summary: Create project note
      security:
        - bearerAuth: []
      parameters:
        - name: project
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                content:
                  type: string
                pinned:
                  type: boolean
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectNote'

  /tasks:
    get:
      tags:
        - Tasks
      summary: List all tasks
      security:
        - bearerAuth: []
      parameters:
        - name: project_id
          in: query
          schema:
            type: integer
        - name: assigned_to_user_id
          in: query
          schema:
            type: integer
        - name: completed
          in: query
          schema:
            type: boolean
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /users/{user}/permissions/{permission}/grant:
    post:
      tags:
        - Permissions
      summary: Grant permission to user
      security:
        - bearerAuth: []
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: integer
        - name: permission
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
      responses:
        '200':
          description: Permission granted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'

security:
  - bearerAuth: []

